version: '2'
services:
  rdc_jhipster-app:
    image: rdc_jhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://rdc_jhipster-mariadb:3306/rdc_jhipster?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  rdc_jhipster-mariadb:
    extends:
      file: mariadb.yml
      service: rdc_jhipster-mariadb
